# Generated by Django 2.2.4 on 2019-09-12 10:27

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCredendial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=1000)),
                ('subject_name', models.CharField(max_length=1000)),
                ('total_questions', models.IntegerField()),
                ('questions_added', models.IntegerField(default=0)),
                ('test_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_in_minutes', models.IntegerField()),
                ('students_allowed', models.CharField(max_length=10000)),
                ('total_allowed_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total', models.IntegerField()),
                ('co1_total', models.IntegerField()),
                ('co2_total', models.IntegerField()),
                ('co3_total', models.IntegerField()),
                ('co4_total', models.IntegerField()),
                ('co5_total', models.IntegerField()),
                ('co6_total', models.IntegerField()),
                ('co7_total', models.IntegerField()),
                ('question_credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.QuestionCredendial')),
                ('rollnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Credentials')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_co', models.IntegerField()),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option_one', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option_two', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option_three', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option_four', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option_one_answer', models.BooleanField(default=False)),
                ('option_two_answer', models.BooleanField(default=False)),
                ('option_three_answer', models.BooleanField(default=False)),
                ('option_four_answer', models.BooleanField(default=False)),
                ('question_credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.QuestionCredendial')),
            ],
        ),
    ]
